export const NUCLEOS = [
  "NEEMec", "NEBEC", "NEEA", "NEECT", "NEEETA",
  "NEEF", "NEEQu", "NEI", "NEM", "AEGIA",
];

export const TEAM_DATA = {
  strategic: [
    { group: "Coordenação", role: "Coord.", members: [
      ["Mariana Guerra", "NEEMec"],
      ["Miguel Paiva", "NEEETA"],
      ["Rafael Caçador", "NEECT"],
      ["Hugo Correia", "NEI"],
    ]},
    { group: "Financeiro", role: "Finan.", members: [
      ["João Tomás", "NEEMec"],
      ["José Santos", "NEEETA"],
      ["José Jordão", "NEECT"],
      ["Beatriz Francisco", "NEI"],
    ]},
  ],
  operational: [
    { group: "Material e Espaço", role: "Logística · Material", members: [
      ["Bernardo Costa", "NEEMec", "Team Leader"],
      ["Francisco Ferreira", "NEEMec"],
      ["Cristiano Oliveira", "NEEA"],
      ["Francisca Duarte", "AEGIA"],
      ["Diogo Santos", "NEEETA"],
      ["Diogo Soares", "NEEF"],
      ["Rúben Formigal", "NEEA"],
    ]},
    { group: "Alimentação e Decoração", role: "Logística · F&B", members: [
      ["Madalena Diogo", "NEECT", "Team Leader"],
      ["Simão Pires", "NEEMec"],
      ["Íris Alves", "NEEA"],
      ["Marta Neves", "NEEF"],
      ["João Guerra", "NEBEC"],
      ["Joaquim Mota", "NEBEC"],
      ["Adriana Rocha", "NEECT"],
    ]},
    { group: "Divulgação", role: "Comunicação", members: [
      ["André Dora", "NEI", "Team Leader"],
      ["João Tavares", "NEECT"],
      ["Pedro Cabrela", "NEM"],
      ["Matilde Lourenço", "NEM"],
      ["Beatriz Barata", "AEGIA"],
      ["Diana Silva", "NEEA"],
      ["Raquel Castro", "NEEQu"],
      ["Catarina Franco", "NEEF"],
    ]},
    { group: "Brindes", role: "Comunicação · Merch", members: [
      ["Gonçalo Cristovão", "NEBEC", "Team Leader"],
      ["Maria Guerra", "NEEMec"],
      ["Gonçalo Bastos", "AEGIA"],
      ["Tiago Ferreira", "NEEETA"],
      ["Alice Calhau", "NEBEC"],
    ]},
    { group: "Parcerias", role: "Relações Externas", members: [
      ["Margarida Ribeiro", "NEI", "Team Leader"],
      ["Angela Ribeiro", "NEI"],
      ["António Camacho", "NEEA"],
      ["Sara Silva", "NEEMec"],
      ["João Matos", "AEGIA"],
      ["Hugo Castro", "NEI"],
    ]},
    { group: "Artistas", role: "Relações Externas · Booking", members: [
      ["Tiago Rocha", "NEEMec", "Team Leader"],
      ["Simão Santos", "NEEETA"],
      ["Gonçalo Crasto", "AEGIA"],
      ["Gonçalo Costa", "NEM"],
      ["Henrique Vieira", "NEM"],
      ["Vasco Vouzela", "NEI"],
    ]},
  ],
};

const countMembers = (groups) => groups.reduce((n, g) => n + g.members.length, 0);

/* Derived so the headline numbers can never drift from TEAM_DATA. */
export const TEAM_COUNTS = {
  strategic: countMembers(TEAM_DATA.strategic),
  operational: countMembers(TEAM_DATA.operational),
  get total() { return this.strategic + this.operational; },
};

const pad2 = (n) => String(n).padStart(2, "0");

/* --------------------------------------------------------------------------
   Media and sponsor data are language-independent apart from their labels,
   so they live once here and get flattened per language below.
   -------------------------------------------------------------------------- */

const GALLERY_MEDIA = [
  { type: "drone",  src: "/gallery/video_drone.mp4", poster: "/gallery/video_drone_poster.webp", meta: "MP4",
    label: { pt: "Aftermovie 2025",      en: "2025 aftermovie" } },
  { type: "tall",   src: "/gallery/1.webp",  meta: "2025 / 01",
    label: { pt: "Público · main stage", en: "Crowd · main stage" } },
  { type: "wide",   src: "/gallery/2.webp",  meta: "2025 / 02",
    label: { pt: "Pôr-do-sol campus",    en: "Sunset over campus" } },
  { type: "square", src: "/gallery/3.webp",  meta: "2025 / 03",
    label: { pt: "Detalhe palco",        en: "Stage detail" } },
  { type: "small",  src: "/gallery/4.webp",  meta: "2025 / 04",
    label: { pt: "Food court",           en: "Food court" } },
  { type: "square", src: "/gallery/5.webp",  meta: "2025 / 05",
    label: { pt: "Equipa dia-D",         en: "Team on event day" } },
  { type: "wide",   src: "/gallery/6.webp",  meta: "2025 / 06",
    label: { pt: "Crowd shot",           en: "Crowd shot" } },
  { type: "square", src: "/gallery/7.webp",  meta: "2025 / 07",
    label: { pt: "Bar · gins",           en: "Gin bar" } },
  { type: "small",  src: "/gallery/8.webp",  meta: "2025 / 08",
    label: { pt: "Photo wall",           en: "Photo wall" } },
  { type: "wide",   src: "/gallery/9.webp",  meta: "2025 / 09",
    label: { pt: "Pista de dança",       en: "Dance floor" } },
  { type: "square", src: "/gallery/10.webp", meta: "2025 / 10",
    label: { pt: "Detalhes",             en: "Details" } },
  { type: "small",  src: "/gallery/11.webp", meta: "2025 / 11",
    label: { pt: "Pré-festa",            en: "Pre-party" } },
];

const SPONSOR_TIERS = [
  {
    kind: "main", name: "MAIN", slots: 1,
    tag: { pt: "Patrocinador principal", en: "Headline sponsor" },
    sponsors: [],
  },
  {
    kind: "gold", name: "GOLD", slots: 7,
    tag: { pt: "Patrocinadores ouro", en: "Gold sponsors" },
    sponsors: [
      { name: "O Cantinho do Santiago", src: "/sponsors/gold/cantinho-de-santiago/cantinho-de-santiago.jpg", url: "https://www.instagram.com/ocantinhodosantiago/" },
      { name: "Chicken in Box",         src: "/sponsors/gold/chicken-in-box/chicken-in-box.jpeg" },
      { name: "Dokk Club",              src: "/sponsors/gold/dokk-club/dokk-club.png" },
      { name: "Maria Lounge Bar",       src: "/sponsors/gold/maria-lounge-bar/maria-lounge-bar.jpeg" },
      { name: "Skydive Dunas",          src: "/sponsors/gold/skydive-dunas/skydives-positive.png", srcDark: "/sponsors/gold/skydive-dunas/skydive-dunas-negative.png", big: true },
      { name: "Salicornia",             src: "/sponsors/gold/salicornia/salicornia-positive.png",  srcDark: "/sponsors/gold/salicornia/salicornia-negative.png",   big: true },
      { name: "Energi JB",              src: "/sponsors/gold/energiJB/energi-JB.png" },
    ],
  },
  {
    kind: "silver", name: "SILVER", slots: 12,
    tag: { pt: "Patrocinadores prata", en: "Silver sponsors" },
    sponsors: [
      { name: "Bolacha Americana",   src: "/sponsors/silver/bolacha-americana/bolacha-americana.png" },
      { name: "Pokebox",             src: "/sponsors/silver/pokebox/pokebox-positive.png", srcDark: "/sponsors/silver/pokebox/pokebox-negative.png", url: "https://pokeboxstore.pt/" },
      { name: "Ferragens de Aveiro", src: "/sponsors/silver/ferragens-de-aveiro/ferragens-de-aveiro.png" },
      { name: "Piano Bar",           src: "/sponsors/silver/piano-bar/piano-bar.png" },
    ],
  },
];

const galleryItems = (lang) => GALLERY_MEDIA.map(({ label, ...media }) => ({ ...media, label: label[lang] }));
const sponsorTiers = (lang) => SPONSOR_TIERS.map(({ tag, ...tier }) => ({ ...tier, tag: tag[lang] }));

export const SITE_CONTENT = {
  pt: {
    nav: {
      about: "Evento",
      lineup: "Cartaz",
      gallery: "Galeria",
      sponsors: "Patrocínios",
      team: "Equipa",
      location: "Local",
      rsvp: "Reservar",
    },
    hero: {
      edition: "3ª Edição · Entrada Livre · 2026",
      date_label: "Data",
      date: "13 Mai 2026",
      hours_label: "Horário",
      hours: "17h00 — 02h00",
      place_label: "Local",
      place: "UA · Campus Santiago",
      city_label: "Cidade",
      city: "Aveiro, PT",
      tagline_top: "Uma noite. Dez núcleos.",
      tagline_bottom: "Mil engenheiros.",
      cta_primary: "Ver informações do local",
      cta_secondary: "Ver cartaz",
      countdown_label: "Contagem decrescente",
      days: "Dias", hours_c: "Horas", mins: "Minutos", secs: "Segundos",
    },
    about: {
      num: "01",
      title: "O Evento",
      meta: "Terceira edição do maior encontro de Engenharias da UA",
      lede: "O encontro de referência das Engenharias da Universidade de Aveiro, onde centenas de futuros engenheiros se reúnem num único pôr-do-sol.",
      body_1: "O Sunset de Engenharias atinge em 2026 a sua terceira edição, consolidando-se como o evento de referência na promoção da coesão e do espírito de corpo entre os estudantes das áreas tecnológicas da Universidade de Aveiro. O que surgiu em 2024 como uma iniciativa de aproximação é hoje um compromisso, reconhecido pela sua capacidade de unir centenas de futuros engenheiros num ambiente de excelência e partilha.",
      body_2: "Mais do que um momento de lazer, a terceira edição simboliza a força de uma comunidade vibrante. Ao celebrarmos este percurso, renovamos a oportunidade para se associarem a um evento que reflete o prestígio, a inovação e a união que definem as Engenharias da UA.",
      stats: [
        ["3ª", "Edição"],
        [String(NUCLEOS.length), "Núcleos envolvidos"],
        [String(TEAM_COUNTS.total), "Organizadores"],
        ["9h", "De festa contínua"],
      ],
    },
    lineup: {
      num: "02",
      title: "Cartaz",
      meta: "Horário contínuo das 17h às 02h.",
      stage: "Palco Principal",
      stage_label: "Palco Principal",
      rows: [
        ["17:00", "ABERTURA", "—"],
        ["17:00 — 19:00", "MICHEL FARIA e Banda", "Pagode"],
        ["19:00 — 22:00", "TOOMANYBROTHERS", "House"],
        ["22:00 — 00:00", "ATMUS", "House"],
        ["00:00 — 02:00", "UTOPIA", "Versátil · Hip Hop Tuga / Throwback"],
        ["02:00", "FIM DO EVENTO", "—"],
      ],
    },
    gallery: {
      num: "03",
      title: "Galeria",
      meta: "Momentos das edições anteriores",
      items: galleryItems("pt"),
    },
    sponsors: {
      num: "04",
      title: "Patrocínios",
      meta: "As marcas que tornam o Sunset possível",
      tiers: sponsorTiers("pt"),
      cta_title: "Quer associar a sua marca ao Sunset?",
      cta_body: "Entre em contacto com a equipa de Relações Externas para receber a proposta detalhada e condições personalizadas.",
      cta_button: "Contactar equipa",
      soon: "Em breve",
      slot_one: "vaga",
      slot_many: "vagas",
      presented_by: "Apresentado por",
    },
    team: {
      num: "05",
      title: "Equipa",
      meta: `${TEAM_COUNTS.total} pessoas. ${NUCLEOS.length} núcleos. Um só evento.`,
      filter_all: "Todos",
      strategic_title: "Parte Estratégica",
      strategic_meta: `${pad2(TEAM_COUNTS.strategic)} · Coordenação + Financeiro`,
      operational_title: "Parte Operacional",
      operational_meta: `${TEAM_COUNTS.operational} · Logística · Comunicação · Relações`,
      member: "Membro",
      show_more: "Ver equipa completa",
      show_less: "Mostrar menos",
    },
    location: {
      num: "06",
      title: "Local",
      meta: "Campus Universitário de Santiago, Universidade de Aveiro",
      address_label: "Morada",
      address: "Campus Universitário de Santiago",
      address_sub: "3810-193 Aveiro, Portugal",
      date_label: "Data & horário",
      date: "13 de Maio de 2026",
      date_sub: "Das 17h00 às 02h00 do dia 14",
      access_label: "Acessos",
      access: "Transportes públicos · Estacionamento no campus",
      access_sub: "Linhas urbanas 1, 4 e 5 · Bicicleta BUGA gratuita",
      entrance_label: "Entrada",
      entrance: "Livre para toda a comunidade UA",
      entrance_sub: "Sem bilhetes.",
      map_label: "Planta do recinto",
      map_sub: "Universidade de Aveiro · Campus de Santiago",
    },
    /* Copy for the RSVP flow — written, but no component consumes it yet. */
    rsvp: {
      title: "Reservar entrada",
      body: "Garanta a sua presença na 3ª edição. Entrada gratuita mediante apresentação de cartão de estudante UA.",
      name: "Nome completo",
      email: "E-mail institucional",
      nucleo: "Núcleo / Curso",
      year: "Ano",
      back: "Voltar",
      next: "Continuar",
      confirm: "Confirmar reserva",
      success_title: "Reserva confirmada",
      success_body: "Receberá um e-mail de confirmação com a sua pulseira digital. Até dia 13 de Maio!",
      close: "Fechar",
    },
    footer: {
      tagline: "Onde o sol se põe e as engenharias se reúnem.",
      org: "Organização",
      org_meta: `${NUCLEOS.length} núcleos · ${TEAM_COUNTS.total} organizadores`,
      nucleos: "Núcleos",
      contact: "Contactos",
      social: "Redes",
      more: "Mais",
      credit: "Feito por",
      copy: "© 2026 Sunset D'Engenharias · Universidade de Aveiro",
      privacy: "Privacidade · Termos",
    },
  },
  en: {
    nav: {
      about: "Event",
      lineup: "Lineup",
      gallery: "Gallery",
      sponsors: "Sponsors",
      team: "Team",
      location: "Venue",
      rsvp: "RSVP",
    },
    hero: {
      edition: "3rd Edition · Free Entry · 2026",
      date_label: "Date",
      date: "May 13, 2026",
      hours_label: "Hours",
      hours: "5 PM — 2 AM",
      place_label: "Venue",
      place: "UA · Santiago Campus",
      city_label: "City",
      city: "Aveiro, PT",
      tagline_top: "One night. Ten student bodies.",
      tagline_bottom: "A thousand engineers.",
      cta_primary: "See venue info",
      cta_secondary: "See lineup",
      countdown_label: "Countdown",
      days: "Days", hours_c: "Hours", mins: "Minutes", secs: "Seconds",
    },
    about: {
      num: "01",
      title: "The Event",
      meta: "Third edition of the University of Aveiro's biggest engineering gathering",
      lede: "The reference gathering for Engineering students at the University of Aveiro, where hundreds of future engineers come together under a single sunset.",
      body_1: "In 2026 Sunset D'Engenharias reaches its third edition, establishing itself as the reference event promoting cohesion and camaraderie among students from the technological areas of the University of Aveiro. What started in 2024 as an initiative of approach is today a commitment, recognized for bringing hundreds of future engineers into an environment of excellence and sharing.",
      body_2: "More than a moment of leisure, this third edition symbolizes the strength of a vibrant community. As we celebrate this journey, we renew the opportunity for brands to associate with an event that reflects the prestige, innovation and union that define Engineering at UA.",
      stats: [
        ["3rd", "Edition"],
        [String(NUCLEOS.length), "Student bodies"],
        [String(TEAM_COUNTS.total), "Organizers"],
        ["9h", "Of continuous festival"],
      ],
    },
    lineup: {
      num: "02",
      title: "Lineup",
      meta: "Continuous schedule from 5 PM to 2 AM.",
      stage: "Main Stage",
      stage_label: "Main Stage",
      rows: [
        ["17:00", "DOORS OPEN", "—"],
        ["17:00 — 19:00", "MICHEL FARIA and Band", "Pagode"],
        ["19:00 — 22:00", "TOOMANYBROTHERS", "House"],
        ["22:00 — 00:00", "ATMUS", "House"],
        ["00:00 — 02:00", "UTOPIA", "Versatile · Hip Hop Tuga / Throwback"],
        ["02:00", "END OF THE EVENT", "—"],
      ],
    },
    gallery: {
      num: "03",
      title: "Gallery",
      meta: "Moments from past editions",
      items: galleryItems("en"),
    },
    sponsors: {
      num: "04",
      title: "Sponsors",
      meta: "The brands that make Sunset possible",
      tiers: sponsorTiers("en"),
      cta_title: "Want to bring your brand to Sunset?",
      cta_body: "Contact our External Relations team for a detailed proposal and custom conditions.",
      cta_button: "Contact team",
      soon: "Coming soon",
      slot_one: "slot",
      slot_many: "slots",
      presented_by: "Presented by",
    },
    team: {
      num: "05",
      title: "Team",
      meta: `${TEAM_COUNTS.total} people. ${NUCLEOS.length} student bodies. One event.`,
      filter_all: "All",
      strategic_title: "Strategic",
      strategic_meta: `${pad2(TEAM_COUNTS.strategic)} · Coordination + Finance`,
      operational_title: "Operational",
      operational_meta: `${TEAM_COUNTS.operational} · Logistics · Comms · Relations`,
      member: "Member",
      show_more: "View full team",
      show_less: "Show less",
    },
    location: {
      num: "06",
      title: "Venue",
      meta: "Santiago University Campus, University of Aveiro",
      address_label: "Address",
      address: "Campus Universitário de Santiago",
      address_sub: "3810-193 Aveiro, Portugal",
      date_label: "Date & hours",
      date: "May 13, 2026",
      date_sub: "From 5 PM to 2 AM the next day",
      access_label: "Access",
      access: "Public transport · On-campus parking",
      access_sub: "Urban lines 1, 4 and 5 · Free BUGA bicycle",
      entrance_label: "Entry",
      entrance: "Free for the whole UA community",
      entrance_sub: "No tickets. Student card recommended.",
      map_label: "Venue map",
      map_sub: "University of Aveiro · Santiago Campus",
    },
    /* Copy for the RSVP flow — written, but no component consumes it yet. */
    rsvp: {
      title: "Reserve entry",
      body: "Secure your spot at the 3rd edition. Free entry with a UA student card.",
      name: "Full name",
      email: "University email",
      nucleo: "Body / Course",
      year: "Year",
      back: "Back",
      next: "Continue",
      confirm: "Confirm RSVP",
      success_title: "RSVP confirmed",
      success_body: "You'll receive a confirmation email with your digital wristband. See you on May 13th!",
      close: "Close",
    },
    footer: {
      tagline: "Where the sun sets and engineering comes together.",
      org: "Organization",
      org_meta: `${NUCLEOS.length} bodies · ${TEAM_COUNTS.total} organizers`,
      nucleos: "Student bodies",
      contact: "Contact",
      social: "Social",
      more: "More",
      credit: "Made by",
      copy: "© 2026 Sunset D'Engenharias · University of Aveiro",
      privacy: "Privacy · Terms",
    },
  },
};
